import jsPDF from 'jspdf';

const MARGIN = 20;
const LINE_HEIGHT = 6.5;
const MAX_WIDTH = 170;
const PAGE_HEIGHT = 297;
const BOTTOM_MARGIN = 25;

function setPdfFont(doc, size = 10, style = 'normal') {
  doc.setFont('times', style);
  doc.setFontSize(size);
}

function checkPageBreak(doc, y, spaceNeeded = LINE_HEIGHT) {
  if (y + spaceNeeded > PAGE_HEIGHT - BOTTOM_MARGIN) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function wrapText(doc, text, x, y) {
  const lines = doc.splitTextToSize(String(text || '—'), MAX_WIDTH) || [];
  doc.text(lines, x, y);
  return y + lines.length * LINE_HEIGHT;
}

function sectionLabel(doc, label, y) {
  setPdfFont(doc, 9, 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text(label.toUpperCase(), MARGIN, y);
  return y + LINE_HEIGHT;
}

function sectionBody(doc, text, y) {
  setPdfFont(doc, 10, 'normal');
  doc.setTextColor(0, 0, 0);
  return wrapText(doc, text, MARGIN, y) + 4;
}

export function downloadVerdictPdf(result, university, country) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  setPdfFont(doc, 10, 'normal');
  let y = MARGIN;

  setPdfFont(doc, 16, 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('One-look verdict', MARGIN, y);
  y += 10;

  setPdfFont(doc, 11, 'normal');
  doc.text(`${result.university || university} · ${result.country || country}`, MARGIN, y);
  y += 12;

  // Worth it?
  y = checkPageBreak(doc, y, 20);
  y = sectionLabel(doc, 'Worth it?', y);
  y = sectionBody(doc, result.isWorthItVerdict || '—', y);
  y = checkPageBreak(doc, y, 0);

  y = checkPageBreak(doc, y, 20);
  y = sectionLabel(doc, 'Reddit mood', y);
  y = sectionBody(doc, result.reviewMood || '—', y);
  y = checkPageBreak(doc, y, 0);

  y = checkPageBreak(doc, y, 30);
  y = sectionLabel(doc, 'Rough yearly cost', y);
  setPdfFont(doc, 10, 'normal');
  doc.setTextColor(0, 0, 0);
  const costs = [
    `₹ ${result.yearlyCostInr || result.yearlyCostInInr || '—'}`,
    `$ ${result.yearlyCostUsd || '—'}`,
    `€ ${result.yearlyCostEur || '—'}`,
  ];
  costs.forEach((line) => {
    y = checkPageBreak(doc, y, LINE_HEIGHT);
    doc.text(line, MARGIN, y);
    y += LINE_HEIGHT;
  });
  y += 4;

  if (result.acceptanceRate) {
    y = checkPageBreak(doc, y, 40);
    y = sectionLabel(doc, 'Acceptance rate', y);
    y = sectionBody(doc, result.acceptanceRate, y);
    setPdfFont(doc, 8, 'normal');
    doc.setTextColor(120, 120, 120);
    y = wrapText(
      doc,
      'Based on publicly available data (e.g. GradCafe, Admit.com, Reddit). Actual rates depend on the university and program.',
      MARGIN,
      y
    );
    y += 6;
    y = checkPageBreak(doc, y, 0);
  }

  y = checkPageBreak(doc, y, 25);
  y = sectionLabel(doc, 'Difficulty level', y);
  y = sectionBody(doc, result.difficultyLevel || '—', y);
  y = checkPageBreak(doc, y, 0);

  if (Array.isArray(result.quickNotes) && result.quickNotes.length > 0) {
    y = checkPageBreak(doc, y, 40);
    y = sectionLabel(doc, 'Quick notes', y);
    setPdfFont(doc, 10, 'normal');
    doc.setTextColor(0, 0, 0);
    result.quickNotes.forEach((note) => {
      y = checkPageBreak(doc, y, 15);
      y = wrapText(doc, '• ' + note, MARGIN, y);
    });
    y += 4;
    y = checkPageBreak(doc, y, 0);
  }

  // Similar universities (text list)

  // Footer on last page
  y = checkPageBreak(doc, y, 15);
  setPdfFont(doc, 8, 'normal');
  doc.setTextColor(140, 140, 140);
  doc.text('Generated by Unora. Verify with official sources.', MARGIN, y);

  const filename = `verdict-${(result.university || university).replace(/\s+/g, '-').slice(0, 30)}.pdf`;
  doc.save(filename);
}
