import jsPDF from 'jspdf';

const MARGIN = 20;
const LINE_HEIGHT = 6;
const MAX_WIDTH = 170;

function wrapText(doc, text, x, y) {
  const lines = doc.splitTextToSize(String(text || '—'), MAX_WIDTH) || [];
  doc.text(lines, x, y);
  return y + lines.length * LINE_HEIGHT;
}

function sectionLabel(doc, label, y) {
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(label.toUpperCase(), MARGIN, y);
  return y + LINE_HEIGHT;
}

function sectionBody(doc, text, y) {
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  return wrapText(doc, text, MARGIN, y) + 4;
}

export function downloadVerdictPdf(result, university, country) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = MARGIN;

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('One-look verdict', MARGIN, y);
  y += 10;

  doc.setFontSize(11);
  doc.text(`${result.university || university} · ${result.country || country}`, MARGIN, y);
  y += 12;

  // Worth it?
  y = sectionLabel(doc, 'Worth it?', y);
  y = sectionBody(doc, result.isWorthItVerdict || '—', y);

  // Reddit mood
  y = sectionLabel(doc, 'Reddit mood', y);
  y = sectionBody(doc, result.reviewMood || '—', y);

  // Rough yearly cost (all three)
  y = sectionLabel(doc, 'Rough yearly cost', y);
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const costs = [
    `₹ ${result.yearlyCostInr || result.yearlyCostInInr || '—'}`,
    `$ ${result.yearlyCostUsd || '—'}`,
    `€ ${result.yearlyCostEur || '—'}`,
  ];
  costs.forEach((line) => {
    doc.text(line, MARGIN, y);
    y += LINE_HEIGHT;
  });
  y += 4;

  // Acceptance rate
  if (result.acceptanceRate) {
    y = sectionLabel(doc, 'Acceptance rate', y);
    y = sectionBody(doc, result.acceptanceRate, y);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    y = wrapText(
      doc,
      'Based on publicly available data (e.g. GradCafe, Admit.com, Reddit). Actual rates depend on the university and program.',
      MARGIN,
      y
    );
    y += 6;
  }

  // Difficulty level
  y = sectionLabel(doc, 'Difficulty level', y);
  y = sectionBody(doc, result.difficultyLevel || '—', y);

  // Quick notes
  if (Array.isArray(result.quickNotes) && result.quickNotes.length > 0) {
    y = sectionLabel(doc, 'Quick notes', y);
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    result.quickNotes.forEach((note) => {
      y = wrapText(doc, '• ' + note, MARGIN, y);
    });
    y += 4;
  }

  // Similar universities (text list)

  // Footer
  y = Math.max(y, 260);
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text('generated by unora :3.', MARGIN, y);

  const filename = `verdict-${(result.university || university).replace(/\s+/g, '-').slice(0, 30)}.pdf`;
  doc.save(filename);
}
